/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mfcal;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.UnsupportedEncodingException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author authorr
 */
public class Fourfra extends javax.swing.JFrame {

    /**
     * Creates new form Fourfra
     */
   
    public Fourfra(int day, int month, int year, int hour) throws FileNotFoundException, IOException {
        initComponents();
        this.day = day;
        this.month = month;
        this.year = year;
        this.hour = hour;
        jLabel1.setText(day + "/" + month + "/" + year + " Hour :" + hour);

        FileReader fileReader = new FileReader(new File("passDats.txt"));

        BufferedReader br = new BufferedReader(fileReader);

        String line = null;
         br.readLine();
        while ((line = br.readLine()) != null) // reading lines until the end of the file
        {
            String[] splitStr = MFCal.decode(line).split("é");
            if (splitStr[0].equals(jLabel1.getText())) {
                jTextArea1.setText(splitStr[1]);
                jButton2.setVisible(false);
            }

        }
        br.close();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("23 Ekim 2016");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Remove TODO");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addGap(65, 65, 65)
                        .addComponent(jButton1)))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton1))
                .addContainerGap(187, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Thfra x = null;
        try {
            x = new Thfra(this.day, this.month, this.year);
        } catch (IOException ex) {
            Logger.getLogger(Fourfra.class.getName()).log(Level.SEVERE, null, ex);
        }
        x.setLocation(this.getLocation());
        x.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String firTex = this.day + "/" + this.month + "/" + this.year + " Hour :" + this.hour + "é";
        String text = jTextArea1.getText();
        String willSend = new String();

        if(text.length() == 0)
            return;
        int counter = 0;
        for(int i = 0 ; i < text.length() ; ++i)
            if(text.charAt(i) == ' ' || text.charAt(i) == '\t')
                ++counter;
        
        if(counter == text.length())
            return;

        FileWriter fileWriter = null;

        firTex += text;

        
        willSend = MFCal.encode(firTex) + "\r\n";

        System.out.println(willSend);
        
        try {
            fileWriter = new FileWriter("passDats.txt", true);
        } catch (IOException ex) {
            Logger.getLogger(Fourfra.class.getName()).log(Level.SEVERE, null, ex);
        }
        BufferedWriter bufferWritter = new BufferedWriter(fileWriter);
        try {
            bufferWritter.append(willSend);

        } catch (IOException ex) {
            Logger.getLogger(Fourfra.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            bufferWritter.close();
        } catch (IOException ex) {
            Logger.getLogger(Fourfra.class.getName()).log(Level.SEVERE, null, ex);
        }

        Thfra x = null;
        try {
            x = new Thfra(day, month, year);
        } catch (IOException ex) {
            Logger.getLogger(Fourfra.class.getName()).log(Level.SEVERE, null, ex);
        }
        x.setLocation(this.getLocation());
        x.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ArrayList<String> a = new ArrayList<String>();
        String firTex = this.day + "/" + this.month + "/" + this.year + " Hour :" + this.hour + "é";
        firTex += jTextArea1.getText();
        
        
        a.add(MFCal.encode(firTex));
        System.out.println(a.get(0));
        try {
            MFCal.deleteFromFiles("passDats.txt", a);
        } catch (IOException ex) {
            Logger.getLogger(Fourfra.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTextArea1.setText("");
        Thfra x = null;
        try {
            x = new Thfra(day, month, year);
        } catch (IOException ex) {
            Logger.getLogger(Fourfra.class.getName()).log(Level.SEVERE, null, ex);
        }
        x.setLocation(this.getLocation());
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
    private int day;
    private int month;
    private int year;
    private int hour;
}
