/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mfcal;

import java.awt.Color;
import java.io.IOException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Wade
 */
public class Secfra extends javax.swing.JFrame {

    /**
     * Creates new form Secfra
     */
   
    // CONSTRUCTOR WILL BE IMPLEMENTED

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public Secfra(int month, int year) {
        
        initComponents();
      
        ArrayList<MyDate> holidays=null;
        String[] monthsOfYear = new String[12];
        this.buttons = new javax.swing.JButton[37];

        MyCalendar mcal = new MyCalendar();

        this.month = month;
        this.year = year;
        try{
         holidays=OfficialHolidays.getHolidays(year);
        }catch(Throwable t){
            System.out.println(t.getMessage());
            System.exit(1);
        }    


        monthsOfYear[0] = "JANUARY";
        monthsOfYear[1] = "FEBRUARY";
        monthsOfYear[2] = "MARCH";
        monthsOfYear[3] = "APRIL";
        monthsOfYear[4] = "MAY";
        monthsOfYear[5] = "JUNE";
        monthsOfYear[6] = "JULY";
        monthsOfYear[7] = "AUGUST";
        monthsOfYear[8] = "SEPTEMBER";
        monthsOfYear[9] = "OCTOBER";
        monthsOfYear[10] = "NOVEMBER";
        monthsOfYear[11] = "DECEMBER";

        buttons[0] = jButton36;
        buttons[1] = jButton37;
        buttons[2] = jButton38;
        buttons[3] = jButton39;
        buttons[4] = jButton40;
        buttons[5] = jButton41;
        buttons[6] = jButton42;
        buttons[7] = jButton43;
        buttons[8] = jButton44;
        buttons[9] = jButton45;
        buttons[10] = jButton46;
        buttons[11] = jButton47;
        buttons[12] = jButton48;
        buttons[13] = jButton49;
        buttons[14] = jButton50;
        buttons[15] = jButton51;
        buttons[16] = jButton52;
        buttons[17] = jButton53;
        buttons[18] = jButton54;
        buttons[19] = jButton55;
        buttons[20] = jButton56;
        buttons[21] = jButton57;
        buttons[22] = jButton58;
        buttons[23] = jButton59;
        buttons[24] = jButton60;
        buttons[25] = jButton61;
        buttons[26] = jButton62;
        buttons[27] = jButton63;
        buttons[28] = jButton64;
        buttons[29] = jButton65;
        buttons[30] = jButton66;
        buttons[31] = jButton67;
        buttons[32] = jButton68;
        buttons[33] = jButton69;
        buttons[34] = jButton70;
        buttons[35] = jButton71;
        buttons[36] = jButton72;

        String[] str = mcal.getMaxDayAndFirstDay(year, month);
        int startBut = Integer.parseInt(str[1]) - 1;
        
        Integer fir = 1;
        buttons[startBut].setText(fir.toString());
        boolean  var=false;
        for (int i = startBut + 1; i < Integer.parseInt(str[0]) + startBut; ++i) {
            var=false;
            ++fir;
            buttons[i].setText(fir.toString());
         
            if(holidays!=null){
                for(int z=0;z<holidays.size();++z)
                {
                    if(holidays.get(z).getDay()==Integer.parseInt(fir.toString()) && holidays.get(z).getMonth()== month && holidays.get(z).getYear()==year)
                        var=true;
                }
            }
            if(var==true)
                buttons[i].setBackground(Color.yellow);
            if(month == 1)
                buttons[startBut].setBackground(Color.yellow);
        }
        
        for (int i = startBut; i < Integer.parseInt(str[0]) + startBut; ++i) {
            Date aDate = new Date(year, month, Integer.parseInt(buttons[i].getText()));
            if(aDate.compareTo(new Date(MFCal.getCurrentYear(), MFCal.getCurrentMonth(), MFCal.getCurrentDay())) < 0) {
                buttons[i].setBackground(Color.GRAY);
            }
        }
        
        for(int z=0;z<buttons.length;++z){
            
            if(buttons[z].getText().equals(""))
                buttons[z].setVisible(false);
                
        }

        jLabel8.setText("Today :   " + MFCal.getCurrentDay() + " " + monthsOfYear[MFCal.getCurrentMonth() - 1] + " " + MFCal.getCurrentYear());
        jLabel10.setText(monthsOfYear[month - 1] + " " + year);

    }
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jButton49 = new javax.swing.JButton();
        jButton50 = new javax.swing.JButton();
        jButton51 = new javax.swing.JButton();
        jButton52 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jButton55 = new javax.swing.JButton();
        jButton56 = new javax.swing.JButton();
        jButton57 = new javax.swing.JButton();
        jButton58 = new javax.swing.JButton();
        jButton59 = new javax.swing.JButton();
        jButton60 = new javax.swing.JButton();
        jButton61 = new javax.swing.JButton();
        jButton62 = new javax.swing.JButton();
        jButton63 = new javax.swing.JButton();
        jButton64 = new javax.swing.JButton();
        jButton65 = new javax.swing.JButton();
        jButton66 = new javax.swing.JButton();
        jButton67 = new javax.swing.JButton();
        jButton68 = new javax.swing.JButton();
        jButton69 = new javax.swing.JButton();
        jButton70 = new javax.swing.JButton();
        jButton71 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButton72 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel3.setText("Wed");

        jLabel4.setText("Thu");

        jLabel5.setText("Fri");

        jLabel6.setText("Sat");

        jLabel7.setText("Sun");

        jLabel1.setText("Mon");

        jLabel2.setText("Tue");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(42, 42, 42))
        );

        jButton36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton36ActionPerformed(evt);
            }
        });

        jButton37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton37ActionPerformed(evt);
            }
        });

        jButton38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton38ActionPerformed(evt);
            }
        });

        jButton39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton39ActionPerformed(evt);
            }
        });

        jButton40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton40ActionPerformed(evt);
            }
        });

        jButton41.setBackground(new java.awt.Color(236, 96, 96));
        jButton41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton41ActionPerformed(evt);
            }
        });

        jButton42.setBackground(new java.awt.Color(236, 96, 96));
        jButton42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton42ActionPerformed(evt);
            }
        });

        jButton43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton43ActionPerformed(evt);
            }
        });

        jButton44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton44ActionPerformed(evt);
            }
        });

        jButton45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton45ActionPerformed(evt);
            }
        });

        jButton46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton46ActionPerformed(evt);
            }
        });

        jButton47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton47ActionPerformed(evt);
            }
        });

        jButton48.setBackground(new java.awt.Color(236, 96, 96));
        jButton48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton48ActionPerformed(evt);
            }
        });

        jButton49.setBackground(new java.awt.Color(236, 96, 96));
        jButton49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton49ActionPerformed(evt);
            }
        });

        jButton50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton50ActionPerformed(evt);
            }
        });

        jButton51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton51ActionPerformed(evt);
            }
        });

        jButton52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton52ActionPerformed(evt);
            }
        });

        jButton53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton53ActionPerformed(evt);
            }
        });

        jButton54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton54ActionPerformed(evt);
            }
        });

        jButton55.setBackground(new java.awt.Color(236, 96, 96));
        jButton55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton55ActionPerformed(evt);
            }
        });

        jButton56.setBackground(new java.awt.Color(236, 96, 96));
        jButton56.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton56ActionPerformed(evt);
            }
        });

        jButton57.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton57ActionPerformed(evt);
            }
        });

        jButton58.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton58ActionPerformed(evt);
            }
        });

        jButton59.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton59ActionPerformed(evt);
            }
        });

        jButton60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton60ActionPerformed(evt);
            }
        });

        jButton61.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton61ActionPerformed(evt);
            }
        });

        jButton62.setBackground(new java.awt.Color(236, 96, 96));
        jButton62.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton62ActionPerformed(evt);
            }
        });

        jButton63.setBackground(new java.awt.Color(236, 96, 96));
        jButton63.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton63ActionPerformed(evt);
            }
        });

        jButton64.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton64ActionPerformed(evt);
            }
        });

        jButton65.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton65ActionPerformed(evt);
            }
        });

        jButton66.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton66ActionPerformed(evt);
            }
        });

        jButton67.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton67ActionPerformed(evt);
            }
        });

        jButton68.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton68ActionPerformed(evt);
            }
        });

        jButton69.setBackground(new java.awt.Color(236, 96, 96));
        jButton69.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton69ActionPerformed(evt);
            }
        });

        jButton70.setBackground(new java.awt.Color(236, 96, 96));
        jButton70.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton70ActionPerformed(evt);
            }
        });

        jButton71.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton71ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Default");

        jButton2.setText("Change Date");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Default");

        jButton72.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton72ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton64, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton65, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton66, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton67, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton68, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton69, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton70, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton71, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton72, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton36, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton37, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton38, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton39, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton40, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton41, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton42, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton43, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton44, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton45, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton46, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton47, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton48, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton49, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton50, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton51, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton52, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton53, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton54, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton55, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton56, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton57, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton58, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton59, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton60, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton61, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton62, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton63, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(108, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton36, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton37, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton38, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton39, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton40, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton41, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton42, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton43, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton44, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton45, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton46, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton47, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton48, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton49, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton50, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton51, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton52, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton53, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton54, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton55, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton56, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton57, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton58, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton59, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton60, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton61, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton62, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton63, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton64, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton65, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton66, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton67, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton68, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton69, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton70, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton71, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton72, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton36ActionPerformed
        String tex = jButton36.getText();
        if (!tex.equals("") && !jButton36.getBackground().equals(Color.GRAY)) {
            Thfra x = null;
            try {
                x = new Thfra(Integer.parseInt(tex), month, year);
            } catch (IOException ex) {
                Logger.getLogger(Secfra.class.getName()).log(Level.SEVERE, null, ex);
            }
            x.setLocation(this.getLocation());
            x.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton36ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Secfrafirst x = new Secfrafirst();

        x.setLocation(this.getLocation());
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton42ActionPerformed
        String tex = jButton42.getText();
        if (!tex.equals("") && !jButton42.getBackground().equals(Color.GRAY)) {
            Thfra x = null;
            try {
                x = new Thfra(Integer.parseInt(tex), month, year);
            } catch (IOException ex) {
                Logger.getLogger(Secfra.class.getName()).log(Level.SEVERE, null, ex);
            }
            x.setLocation(this.getLocation());
            x.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton42ActionPerformed

    private void jButton49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton49ActionPerformed
        String tex = jButton49.getText();
        if (!tex.equals("") && !jButton49.getBackground().equals(Color.GRAY)) {
            Thfra x = null;
            try {
                x = new Thfra(Integer.parseInt(tex), month, year);
            } catch (IOException ex) {
                Logger.getLogger(Secfra.class.getName()).log(Level.SEVERE, null, ex);
            }
            x.setLocation(this.getLocation());
            x.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton49ActionPerformed

    private void jButton44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton44ActionPerformed
        String tex = jButton44.getText();
        if (!tex.equals("") && !jButton44.getBackground().equals(Color.GRAY)) {
            Thfra x = null;
            try {
                x = new Thfra(Integer.parseInt(tex), month, year);
            } catch (IOException ex) {
                Logger.getLogger(Secfra.class.getName()).log(Level.SEVERE, null, ex);
            }
            x.setLocation(this.getLocation());
            x.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton44ActionPerformed

    private void jButton71ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton71ActionPerformed
        String tex = jButton71.getText();
        if (!tex.equals("") && !jButton71.getBackground().equals(Color.GRAY)) {
            Thfra x = null;
            try {
                x = new Thfra(Integer.parseInt(tex), month, year);
            } catch (IOException ex) {
                Logger.getLogger(Secfra.class.getName()).log(Level.SEVERE, null, ex);
            }
            x.setLocation(this.getLocation());
            x.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton71ActionPerformed

    private void jButton37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton37ActionPerformed
        String tex = jButton37.getText();
        if (!tex.equals("") && !jButton37.getBackground().equals(Color.GRAY)) {
            Thfra x = null;
            try {
                x = new Thfra(Integer.parseInt(tex), month, year);
            } catch (IOException ex) {
                Logger.getLogger(Secfra.class.getName()).log(Level.SEVERE, null, ex);
            }
            x.setLocation(this.getLocation());
            x.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton37ActionPerformed

    private void jButton38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton38ActionPerformed
        String tex = jButton38.getText();
        if (!tex.equals("") && !jButton38.getBackground().equals(Color.GRAY)) {
            Thfra x = null;
            try {
                x = new Thfra(Integer.parseInt(tex), month, year);
            } catch (IOException ex) {
                Logger.getLogger(Secfra.class.getName()).log(Level.SEVERE, null, ex);
            }
            x.setLocation(this.getLocation());
            x.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton38ActionPerformed

    private void jButton39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton39ActionPerformed
        String tex = jButton39.getText();
        if (!tex.equals("") && !jButton39.getBackground().equals(Color.GRAY)) {
            Thfra x = null;
            try {
                x = new Thfra(Integer.parseInt(tex), month, year);
            } catch (IOException ex) {
                Logger.getLogger(Secfra.class.getName()).log(Level.SEVERE, null, ex);
            }
            x.setLocation(this.getLocation());
            x.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton39ActionPerformed

    private void jButton40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton40ActionPerformed
        String tex = jButton40.getText();
        if (!tex.equals("") && !jButton40.getBackground().equals(Color.GRAY)) {
            Thfra x = null;
            try {
                x = new Thfra(Integer.parseInt(tex), month, year);
            } catch (IOException ex) {
                Logger.getLogger(Secfra.class.getName()).log(Level.SEVERE, null, ex);
            }
            x.setLocation(this.getLocation());
            x.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton40ActionPerformed

    private void jButton41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton41ActionPerformed
        String tex = jButton41.getText();
        if (!tex.equals("") && !jButton41.getBackground().equals(Color.GRAY)) {
            Thfra x = null;
            try {
                x = new Thfra(Integer.parseInt(tex), month, year);
            } catch (IOException ex) {
                Logger.getLogger(Secfra.class.getName()).log(Level.SEVERE, null, ex);
            }
            x.setLocation(this.getLocation());
            x.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton41ActionPerformed

    private void jButton43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton43ActionPerformed
        String tex = jButton43.getText();
        if (!tex.equals("") && !jButton43.getBackground().equals(Color.GRAY)) {
            Thfra x = null;
            try {
                x = new Thfra(Integer.parseInt(tex), month, year);
            } catch (IOException ex) {
                Logger.getLogger(Secfra.class.getName()).log(Level.SEVERE, null, ex);
            }
            x.setLocation(this.getLocation());
            x.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton43ActionPerformed

    private void jButton45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton45ActionPerformed
        String tex = jButton45.getText();
        if (!tex.equals("") && !jButton45.getBackground().equals(Color.GRAY)) {
            Thfra x = null;
            try {
                x = new Thfra(Integer.parseInt(tex), month, year);
            } catch (IOException ex) {
                Logger.getLogger(Secfra.class.getName()).log(Level.SEVERE, null, ex);
            }
            x.setLocation(this.getLocation());
            x.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton45ActionPerformed

    private void jButton46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton46ActionPerformed
        String tex = jButton46.getText();
        if (!tex.equals("") && !jButton46.getBackground().equals(Color.GRAY)) {
            Thfra x = null;
            try {
                x = new Thfra(Integer.parseInt(tex), month, year);
            } catch (IOException ex) {
                Logger.getLogger(Secfra.class.getName()).log(Level.SEVERE, null, ex);
            }
            x.setLocation(this.getLocation());
            x.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton46ActionPerformed

    private void jButton47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton47ActionPerformed
        String tex = jButton47.getText();
        if (!tex.equals("") && !jButton47.getBackground().equals(Color.GRAY)) {
            Thfra x = null;
            try {
                x = new Thfra(Integer.parseInt(tex), month, year);
            } catch (IOException ex) {
                Logger.getLogger(Secfra.class.getName()).log(Level.SEVERE, null, ex);
            }
            x.setLocation(this.getLocation());
            x.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton47ActionPerformed

    private void jButton48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton48ActionPerformed
        String tex = jButton48.getText();
        if (!tex.equals("") && !jButton48.getBackground().equals(Color.GRAY)) {
            Thfra x = null;
            try {
                x = new Thfra(Integer.parseInt(tex), month, year);
            } catch (IOException ex) {
                Logger.getLogger(Secfra.class.getName()).log(Level.SEVERE, null, ex);
            }
            x.setLocation(this.getLocation());
            x.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton48ActionPerformed

    private void jButton50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton50ActionPerformed
        String tex = jButton50.getText();
        if (!tex.equals("") && !jButton50.getBackground().equals(Color.GRAY)) {
            Thfra x = null;
            try {
                x = new Thfra(Integer.parseInt(tex), month, year);
            } catch (IOException ex) {
                Logger.getLogger(Secfra.class.getName()).log(Level.SEVERE, null, ex);
            }
            x.setLocation(this.getLocation());
            x.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton50ActionPerformed

    private void jButton51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton51ActionPerformed
        String tex = jButton51.getText();
        if (!tex.equals("") && !jButton51.getBackground().equals(Color.GRAY)) {
            Thfra x = null;
            try {
                x = new Thfra(Integer.parseInt(tex), month, year);
            } catch (IOException ex) {
                Logger.getLogger(Secfra.class.getName()).log(Level.SEVERE, null, ex);
            }
            x.setLocation(this.getLocation());
            x.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton51ActionPerformed

    private void jButton52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton52ActionPerformed
        String tex = jButton52.getText();
        if (!tex.equals("") && !jButton52.getBackground().equals(Color.GRAY)) {
            Thfra x = null;
            try {
                x = new Thfra(Integer.parseInt(tex), month, year);
            } catch (IOException ex) {
                Logger.getLogger(Secfra.class.getName()).log(Level.SEVERE, null, ex);
            }
            x.setLocation(this.getLocation());
            x.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton52ActionPerformed

    private void jButton53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton53ActionPerformed
        String tex = jButton53.getText();
        if (!tex.equals("") && !jButton53.getBackground().equals(Color.GRAY)) {
            Thfra x = null;
            try {
                x = new Thfra(Integer.parseInt(tex), month, year);
            } catch (IOException ex) {
                Logger.getLogger(Secfra.class.getName()).log(Level.SEVERE, null, ex);
            }
            x.setLocation(this.getLocation());
            x.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton53ActionPerformed

    private void jButton54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton54ActionPerformed
        String tex = jButton54.getText();
        if (!tex.equals("") && !jButton54.getBackground().equals(Color.GRAY)) {
            Thfra x = null;
            try {
                x = new Thfra(Integer.parseInt(tex), month, year);
            } catch (IOException ex) {
                Logger.getLogger(Secfra.class.getName()).log(Level.SEVERE, null, ex);
            }
            x.setLocation(this.getLocation());
            x.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton54ActionPerformed

    private void jButton55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton55ActionPerformed
        String tex = jButton55.getText();
        if (!tex.equals("") && !jButton55.getBackground().equals(Color.GRAY)) {
            Thfra x = null;
            try {
                x = new Thfra(Integer.parseInt(tex), month, year);
            } catch (IOException ex) {
                Logger.getLogger(Secfra.class.getName()).log(Level.SEVERE, null, ex);
            }
            x.setLocation(this.getLocation());
            x.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton55ActionPerformed

    private void jButton56ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton56ActionPerformed
        String tex = jButton56.getText();
        if (!tex.equals("") && !jButton56.getBackground().equals(Color.GRAY)) {
            Thfra x = null;
            try {
                x = new Thfra(Integer.parseInt(tex), month, year);
            } catch (IOException ex) {
                Logger.getLogger(Secfra.class.getName()).log(Level.SEVERE, null, ex);
            }
            x.setLocation(this.getLocation());
            x.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton56ActionPerformed

    private void jButton57ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton57ActionPerformed
        String tex = jButton57.getText();
        if (!tex.equals("") && !jButton57.getBackground().equals(Color.GRAY)) {
            Thfra x = null;
            try {
                x = new Thfra(Integer.parseInt(tex), month, year);
            } catch (IOException ex) {
                Logger.getLogger(Secfra.class.getName()).log(Level.SEVERE, null, ex);
            }
            x.setLocation(this.getLocation());
            x.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton57ActionPerformed

    private void jButton58ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton58ActionPerformed
        String tex = jButton58.getText();
        if (!tex.equals("") && !jButton58.getBackground().equals(Color.GRAY)) {
            Thfra x = null;
            try {
                x = new Thfra(Integer.parseInt(tex), month, year);
            } catch (IOException ex) {
                Logger.getLogger(Secfra.class.getName()).log(Level.SEVERE, null, ex);
            }
            x.setLocation(this.getLocation());
            x.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton58ActionPerformed

    private void jButton59ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton59ActionPerformed
        String tex = jButton59.getText();
        if (!tex.equals("") && !jButton59.getBackground().equals(Color.GRAY)) {
            Thfra x = null;
            try {
                x = new Thfra(Integer.parseInt(tex), month, year);
            } catch (IOException ex) {
                Logger.getLogger(Secfra.class.getName()).log(Level.SEVERE, null, ex);
            }
            x.setLocation(this.getLocation());
            x.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton59ActionPerformed

    private void jButton60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton60ActionPerformed
        String tex = jButton60.getText();
        if (!tex.equals("") && !jButton60.getBackground().equals(Color.GRAY)) {
            Thfra x = null;
            try {
                x = new Thfra(Integer.parseInt(tex), month, year);
            } catch (IOException ex) {
                Logger.getLogger(Secfra.class.getName()).log(Level.SEVERE, null, ex);
            }
            x.setLocation(this.getLocation());
            x.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton60ActionPerformed

    private void jButton61ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton61ActionPerformed
        String tex = jButton61.getText();
        if (!tex.equals("") && !jButton61.getBackground().equals(Color.GRAY)) {
            Thfra x = null;
            try {
                x = new Thfra(Integer.parseInt(tex), month, year);
            } catch (IOException ex) {
                Logger.getLogger(Secfra.class.getName()).log(Level.SEVERE, null, ex);
            }
            x.setLocation(this.getLocation());
            x.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton61ActionPerformed

    private void jButton62ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton62ActionPerformed
        String tex = jButton62.getText();
        if (!tex.equals("") && !jButton62.getBackground().equals(Color.GRAY)) {
            Thfra x = null;
            try {
                x = new Thfra(Integer.parseInt(tex), month, year);
            } catch (IOException ex) {
                Logger.getLogger(Secfra.class.getName()).log(Level.SEVERE, null, ex);
            }
            x.setLocation(this.getLocation());
            x.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton62ActionPerformed

    private void jButton63ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton63ActionPerformed
        String tex = jButton63.getText();
        if (!tex.equals("") && !jButton63.getBackground().equals(Color.GRAY)) {
            Thfra x = null;
            try {
                x = new Thfra(Integer.parseInt(tex), month, year);
            } catch (IOException ex) {
                Logger.getLogger(Secfra.class.getName()).log(Level.SEVERE, null, ex);
            }
            x.setLocation(this.getLocation());
            x.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton63ActionPerformed

    private void jButton64ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton64ActionPerformed
        String tex = jButton64.getText();
        if (!tex.equals("") && !jButton64.getBackground().equals(Color.GRAY)) {
            Thfra x = null;
            try {
                x = new Thfra(Integer.parseInt(tex), month, year);
            } catch (IOException ex) {
                Logger.getLogger(Secfra.class.getName()).log(Level.SEVERE, null, ex);
            }
            x.setLocation(this.getLocation());
            x.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton64ActionPerformed

    private void jButton65ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton65ActionPerformed
        String tex = jButton65.getText();
        if (!tex.equals("") && !jButton65.getBackground().equals(Color.GRAY)) {
            Thfra x = null;
            try {
                x = new Thfra(Integer.parseInt(tex), month, year);
            } catch (IOException ex) {
                Logger.getLogger(Secfra.class.getName()).log(Level.SEVERE, null, ex);
            }
            x.setLocation(this.getLocation());
            x.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton65ActionPerformed

    private void jButton66ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton66ActionPerformed
        String tex = jButton66.getText();
        if (!tex.equals("") && !jButton66.getBackground().equals(Color.GRAY)) {
            Thfra x = null;
            try {
                x = new Thfra(Integer.parseInt(tex), month, year);
            } catch (IOException ex) {
                Logger.getLogger(Secfra.class.getName()).log(Level.SEVERE, null, ex);
            }
            x.setLocation(this.getLocation());
            x.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton66ActionPerformed

    private void jButton67ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton67ActionPerformed
        String tex = jButton67.getText();
        if (!tex.equals("") && !jButton67.getBackground().equals(Color.GRAY)) {
            Thfra x = null;
            try {
                x = new Thfra(Integer.parseInt(tex), month, year);
            } catch (IOException ex) {
                Logger.getLogger(Secfra.class.getName()).log(Level.SEVERE, null, ex);
            }
            x.setLocation(this.getLocation());
            x.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton67ActionPerformed

    private void jButton68ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton68ActionPerformed
        String tex = jButton68.getText();
        if (!tex.equals("") && !jButton68.getBackground().equals(Color.GRAY)) {
            Thfra x = null;
            try {
                x = new Thfra(Integer.parseInt(tex), month, year);
            } catch (IOException ex) {
                Logger.getLogger(Secfra.class.getName()).log(Level.SEVERE, null, ex);
            }
            x.setLocation(this.getLocation());
            x.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton68ActionPerformed

    private void jButton69ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton69ActionPerformed
        String tex = jButton69.getText();
        if (!tex.equals("") && !jButton69.getBackground().equals(Color.GRAY)) {
            Thfra x = null;
            try {
                x = new Thfra(Integer.parseInt(tex), month, year);
            } catch (IOException ex) {
                Logger.getLogger(Secfra.class.getName()).log(Level.SEVERE, null, ex);
            }
            x.setLocation(this.getLocation());
            x.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton69ActionPerformed

    private void jButton70ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton70ActionPerformed
        String tex = jButton70.getText();
        if (!tex.equals("") && !jButton70.getBackground().equals(Color.GRAY)) {
            Thfra x = null;
            try {
                x = new Thfra(Integer.parseInt(tex), month, year);
            } catch (IOException ex) {
                Logger.getLogger(Secfra.class.getName()).log(Level.SEVERE, null, ex);
            }
            x.setLocation(this.getLocation());
            x.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton70ActionPerformed

    private void jButton72ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton72ActionPerformed
        String tex = jButton72.getText();
        if (!tex.equals("") && !jButton72.getBackground().equals(Color.GRAY)) {
            Thfra x = null;
            try {
                x = new Thfra(Integer.parseInt(tex), month, year);
            } catch (IOException ex) {
                Logger.getLogger(Secfra.class.getName()).log(Level.SEVERE, null, ex);
            }
            x.setLocation(this.getLocation());
            x.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jButton72ActionPerformed

    /**
     * @param args the command line arguments
     */
    private int month;
    private int year;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton49;
    private javax.swing.JButton jButton50;
    private javax.swing.JButton jButton51;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton55;
    private javax.swing.JButton jButton56;
    private javax.swing.JButton jButton57;
    private javax.swing.JButton jButton58;
    private javax.swing.JButton jButton59;
    private javax.swing.JButton jButton60;
    private javax.swing.JButton jButton61;
    private javax.swing.JButton jButton62;
    private javax.swing.JButton jButton63;
    private javax.swing.JButton jButton64;
    private javax.swing.JButton jButton65;
    private javax.swing.JButton jButton66;
    private javax.swing.JButton jButton67;
    private javax.swing.JButton jButton68;
    private javax.swing.JButton jButton69;
    private javax.swing.JButton jButton70;
    private javax.swing.JButton jButton71;
    private javax.swing.JButton jButton72;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    private javax.swing.JButton[] buttons;
}
